using System.Windows.Controls;

namespace RetailStoreInventory.Desktop.Views
{
    /// <summary>
    /// Code-behind file for ProductsView.xaml
    /// 
    /// This file contains the minimal code needed to support the XAML view.
    /// In MVVM architecture, most logic goes in the ViewModel, not here.
    /// 
    /// This class inherits from UserControl, which matches the XAML declaration.
    /// The partial keyword allows the XAML compiler to merge this with the XAML-generated code.
    /// </summary>
    public partial class ProductsView : UserControl
    {
        /// <summary>
        /// Initializes a new instance of the ProductsView.
        /// Calls InitializeComponent() to set up the XAML-defined UI elements.
        /// </summary>
        public ProductsView()
        {
            // This method is auto-generated by the XAML compiler
            // It sets up all the UI controls defined in the XAML file
            InitializeComponent();
        }
    }
}
